//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "api_key_exchange_tokens")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tenant_id: Uuid,
    pub name: String,
    pub token_hash: String,
    pub token_prefix: String,
    pub role_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub expires_at: DateTimeWithTimeZone,
    pub api_key_expires_at: Option<DateTimeWithTimeZone>,
    pub max_usage: i32,
    pub used_count: i32,
    pub created_by: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
