//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tenant_id: Uuid,
    pub name: String,
    pub mime_type: String,
    pub size: i64,
    pub content_hash: String,
    pub content_hash_algo: String,
    pub content_hash_fast: Option<String>,
    pub storage_backend: String,
    pub bucket: String,
    pub storage_key: String,
    pub multipart_upload_id: Option<String>,
    pub status: String,
    pub status_reason: Option<String>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub purge_at: Option<DateTimeWithTimeZone>,
    pub deleted_by: Option<Uuid>,
    pub uploaded_by: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub created_by: Uuid,
    pub updated_by: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
