//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "file_uploads")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub tenant_id: Uuid,
    pub file_name: String,
    pub mime_type_hint: Option<String>,
    pub expected_size: i64,
    pub expected_hash: Option<String>,
    pub expected_hash_algo: String,
    pub part_size: i64,
    pub parts_total: i32,
    pub parts_received: i32,
    pub storage_backend: String,
    pub bucket: String,
    pub temp_key: String,
    pub s3_upload_id: Option<String>,
    pub status: String,
    pub status_reason: Option<String>,
    pub expires_at: DateTimeWithTimeZone,
    pub expired_at: Option<DateTimeWithTimeZone>,
    pub completed_file_id: Option<Uuid>,
    pub expected_hash_fast: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub created_by: Uuid,
    pub updated_by: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
