//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "i18n_entries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub namespace: String,
    pub key: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    /// State machine: `active` | `stale`.
    pub status: String,
    pub last_seen_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::i18n_entry_locations::Entity")]
    I18nEntryLocations,
}

impl Related<super::i18n_entry_locations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::I18nEntryLocations.def()
    }
}
