//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "i18n_entry_locations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub entry_id: Uuid,
    pub file_path: String,
    pub line: i32,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::i18n_entries::Entity",
        from = "Column::EntryId",
        to = "super::i18n_entries::Column::Id",
        on_delete = "Cascade"
    )]
    I18nEntries,
}

impl Related<super::i18n_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::I18nEntries.def()
    }
}
