//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sys_role_template_permissions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub template_id: Uuid,
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "String(StringLen::N(64))"
    )]
    pub obj: String,
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "String(StringLen::N(32))"
    )]
    pub act: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
