use axum::extract::FromRequestParts;
use axum::http::request::Parts;
use loco_rs::app::AppContext;

use crate::middleware::tracing::{RequestId, TraceId};

/// Request-level metadata for audit logging and tracing.
///
/// Extracted as an axum `FromRequestParts` extractor (same pattern as `TenantContext`).
///
/// `trace_id` and `request_id` are injected by [`crate::middleware::tracing::TracingLayer`]
/// before this extractor runs. `ip_address` and `user_agent` are read from headers.
#[derive(Clone, Debug)]
pub struct RequestMeta {
    /// Distributed trace identifier (UUIDv4). Either propagated from the
    /// `X-Trace-Id` request header or freshly generated by `TracingLayer`.
    pub trace_id: String,
    /// Per-request identifier (UUIDv7). Always generated fresh by `TracingLayer`.
    pub request_id: Option<String>,
    pub ip_address: Option<String>,
    pub user_agent: Option<String>,
}

impl FromRequestParts<AppContext> for RequestMeta {
    type Rejection = loco_rs::Error;

    async fn from_request_parts(
        parts: &mut Parts,
        _state: &AppContext,
    ) -> Result<Self, Self::Rejection> {
        // trace_id and request_id are set by TracingLayer in extensions.
        let trace_id = parts
            .extensions
            .get::<TraceId>()
            .map_or_else(|| uuid::Uuid::new_v4().to_string(), |t| t.0.clone());

        let request_id = parts.extensions.get::<RequestId>().map(|r| r.0.clone());

        // ip_address: prefer X-Forwarded-For, then X-Real-IP
        let ip_address = parts
            .headers
            .get("x-forwarded-for")
            .and_then(|v| v.to_str().ok())
            .map(|v| v.split(',').next().unwrap_or(v).trim().to_string())
            .or_else(|| {
                parts
                    .headers
                    .get("x-real-ip")
                    .and_then(|v| v.to_str().ok())
                    .map(String::from)
            });

        // user_agent
        let user_agent = parts
            .headers
            .get(axum::http::header::USER_AGENT)
            .and_then(|v| v.to_str().ok())
            .map(String::from);

        Ok(Self {
            trace_id,
            request_id,
            ip_address,
            user_agent,
        })
    }
}
